### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by ad2969** [onlinkers/event-discovery-api#11]
# TODOS
Things that are marked as `// TODO` in the app
Next Available Index: 10

### Only Frontend
- [ ] Setup default images (profile photos and event marker/cover photo) [1]
- [ ] On sign up, username needs to take email if no username is provided [2]

### Only Backend
- [x] Make event schema 'hosts' property a required field (needs login stuff done first) [5]
- [x] Validate eventsInvolved and eventsHosted on creating and updating a user [7]
- [x] Make location a necessary field events [8]
- [ ] Implement permissions for who can edit categories [9]

### Frontend + Backend
- [ ] Error handlers for requests (frontend only now) [3]
- [ ] Limiting number of text in title (100 on backend, need frontend) [4]
- [ ] Limiting number of text in tags (30 on backend, need frontend) [6]
