### ISSUE TITLE
[FR] User Data Endpoints

### ISSUE THREAD

**Issue by ad2969** [onlinkers/event-discovery-api#3]
# User Data Endpoints

### Description of the feature
* Setup endpoints for user data

### Purpose of the feature
* Allow db manipulation for users

### Tasks to complete
- [x] GET all
- [x] GET one by id
- [x] POST one
- [x] PUT one by id
- [x] DELETE one by id
