### ISSUE TITLE
[FR] API-Blueprinting and Dredd

### ISSUE THREAD

**Issue by ad2969** [onlinkers/event-discovery-api#31]
# Feature Name

### Description of the feature
* Hehe scalability boom boom.

### Purpose of the feature
* Help people understand the different endpoints and setup tests

### Tasks to complete
- [x] Choose good package to use
- [ ] Setup api blueprints
- [ ] Setup testing
- [ ] Setup with CI
