### ISSUE TITLE
[FR] Event Data Endpoints

### ISSUE THREAD

**Issue by ad2969** [onlinkers/event-discovery-api#4]
# Event Data Endpoints

### Description of the feature
* Setup endpoints for event data

### Purpose of the feature
* Allow db manipulation for events

### Tasks to complete
- [ ] GET all
- [ ] GET one by id
- [ ] POST one
- [ ] PUT one by id
- [ ] DELETE one by id
