### ISSUE TITLE
[SCOPE] Circles

### ISSUE THREAD

**Issue by ad2969** [onlinkers/event-discovery-api#46]
# Circles

### Description of the feature
* Circles allow users to essentially 'make friends' and connect with others around them.

### Purpose of the feature
* Allow users to 'find each other'
* (possibly) limit user-user interaction, so as not to overload the system

### Tasks to complete
- [ ] Scope out database structure
- [ ] What kind of data is needed for endpoints
- [ ] Any new technologies that will help?
