### ISSUE TITLE
[FR] Endpoints for specific event data

### ISSUE THREAD

**Issue by ad2969** [onlinkers/event-discovery-api#5]
# Endpoints to GET specific event data
 - Also need to refactor old UPDATE endpoints to do it correctly (refer to APIARY docs)

### Description of the feature
* Ability to get data based on specific parameters

### Purpose of the feature
* Allow some map navigation features

### Tasks to complete
- [x] GET events by location
> Think of proximity and how to make that dynamic
- [x] PUT events & user
- [x] POST - add an event host (update event and user)
